services:
  xiaozhi-esp32-server:
    image: xiaozhi-esp32-server:0213
    container_name: xiaozhi-esp32-server
    restart: always
    #security_opt:
    #  - seccomp:unconfined
    ports:
      - "9005:8000"
    volumes:
      - ./config.yaml:/opt/xiaozhi-es32-server/config.yaml
      - ./models:/opt/xiaozhi-es32-server/models



